// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odxditsaaddeeufjkmmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9keGRpdHNhYWRkZWV1ZmprbW11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyMTU0ODksImV4cCI6MjA3OTc5MTQ4OX0.YzqZA-JJBxUzAxvTGWDv10nV87qffVKJ_qfNUzb5tU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});